In [1]:
pip install --upgrade tensorflow

Requirement already up-to-date: tensorflow in c:\users\laksh\appdata\roaming\python\python38\site-packages (2.6.0)
Note: you may need to restart the kernel to use updated packages.


In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

from keras.models import Sequential
from keras.layers import Dense

In [3]:
data = load_breast_cancer()


In [4]:
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [5]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [6]:
print(data['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [7]:
data['data'].shape

(569, 30)

In [8]:
data['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [9]:

data['data'][0]

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [10]:
#Prints Feature names along with the values of the first tumor
j=0
for i in data['feature_names']:
    print(i,':',data['data'][0][j])
    j=j+1
    

mean radius : 17.99
mean texture : 10.38
mean perimeter : 122.8
mean area : 1001.0
mean smoothness : 0.1184
mean compactness : 0.2776
mean concavity : 0.3001
mean concave points : 0.1471
mean symmetry : 0.2419
mean fractal dimension : 0.07871
radius error : 1.095
texture error : 0.9053
perimeter error : 8.589
area error : 153.4
smoothness error : 0.006399
compactness error : 0.04904
concavity error : 0.05373
concave points error : 0.01587
symmetry error : 0.03003
fractal dimension error : 0.006193
worst radius : 25.38
worst texture : 17.33
worst perimeter : 184.6
worst area : 2019.0
worst smoothness : 0.1622
worst compactness : 0.6656
worst concavity : 0.7119
worst concave points : 0.2654
worst symmetry : 0.4601
worst fractal dimension : 0.1189


In [11]:
#These features are going to be the input to help us detect the type of cancer.

In [12]:
data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [13]:
data['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [14]:
data['filename']

'C:\\Users\\laksh\\anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\breast_cancer.csv'

In [15]:
feature = data['data']

In [16]:
label = data['target']

In [17]:
#Standardizing feature values
scale = StandardScaler()
feature = scale.fit_transform(feature)


In [18]:
#Prints Feature names along with the values of the first tumor
j=0
for i in data['feature_names']:
    print(i,':',feature[0][j])
    j=j+1
    

mean radius : 1.0970639814699807
mean texture : -2.0733350146975935
mean perimeter : 1.2699336881399383
mean area : 0.9843749048031144
mean smoothness : 1.568466329243428
mean compactness : 3.2835146709868264
mean concavity : 2.652873983743168
mean concave points : 2.532475216403245
mean symmetry : 2.2175150059646405
mean fractal dimension : 2.255746885296269
radius error : 2.4897339267376193
texture error : -0.5652650590684639
perimeter error : 2.833030865855184
area error : 2.4875775569611043
smoothness error : -0.21400164666895383
compactness error : 1.3168615683959484
concavity error : 0.72402615808036
concave points error : 0.6608199414286064
symmetry error : 1.1487566671861758
fractal dimension error : 0.9070830809973359
worst radius : 1.8866896251792757
worst texture : -1.3592934737640827
worst perimeter : 2.3036006236225606
worst area : 2.0012374893299207
worst smoothness : 1.3076862710715387
worst compactness : 2.616665023512603
worst concavity : 2.1095263465722556
worst conca

In [19]:
j=0
for i in data['feature_names']:
    print(i,':',feature[5][j])
    j=j+1
print(data['target_names'][[label[5]]],label[5])

mean radius : -0.47637466522134253
mean texture : -0.8353353034209873
mean perimeter : -0.38714806746331654
mean area : -0.5056504544836544
mean smoothness : 2.237421483589421
mean compactness : 1.2443354863901803
mean concavity : 0.8663015959315467
mean concave points : 0.8246556464496959
mean symmetry : 1.005401797785333
mean fractal dimension : 1.8900050384577884
radius error : -0.25507029351590493
texture error : -0.5926616519172156
perimeter error : -0.3213041853640514
area error : -0.28925821666260243
smoothness error : 0.1563467021771524
compactness error : 0.44554364864660323
concavity error : 0.16002519787921415
concave points error : -0.06912355365771157
symmetry error : 0.13411880734830423
fractal dimension error : 0.4868458399286153
worst radius : -0.16549824711686112
worst texture : -0.31383633263536465
worst perimeter : -0.1150094562171625
worst area : -0.24432020786226535
worst smoothness : 2.04851283483916
worst compactness : 1.7216164423470515
worst concavity : 1.26324

In [20]:
df= pd.DataFrame(feature, columns = data['feature_names'])

In [21]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0     1.097064     -2.073335        1.269934   0.984375         1.568466   
1     1.829821     -0.353632        1.685955   1.908708        -0.826962   
2     1.579888      0.456187        1.566503   1.558884         0.942210   
3    -0.768909      0.253732       -0.592687  -0.764464         3.283553   
4     1.750297     -1.151816        1.776573   1.826229         0.280372   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0          3.283515        2.652874             2.532475       2.217515   
1         -0.487072       -0.023846             0.548144       0.001392   
2          1.052926        1.363478             2.037231       0.939685   
3          3.402909        1.915897             1.451707       2.867383   
4          0.539340        1.371011             1.428493      -0.009560   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                2.255747  ...      1.886690      -1.359293         2.303601   
1               -0.868652  ...      1.805927      -0.369203         1.535126   
2               -0.398008  ...      1.511870      -0.023974         1.347475   
3                4.910919  ...     -0.281464       0.133984        -0.249939   
4               -0.562450  ...      1.298575      -1.466770         1.338539   

   worst area  worst smoothness  worst compactness  worst concavity  \
0    2.001237          1.307686           2.616665         2.109526   
1    1.890489         -0.375612          -0.430444        -0.146749   
2    1.456285          0.527407           1.082932         0.854974   
3   -0.550021          3.394275           3.893397         1.989588   
4    1.220724          0.220556          -0.313395         0.613179   

   worst concave points  worst symmetry  worst fractal dimension  
0              2.296076        2.750622                 1.937015  
1              1.087084       -0.243890                 0.281190  
2              1.955000        1.152255                 0.201391  
3              2.175786        6.046041                 4.935010  
4              0.729259       -0.868353                -0.397100  

[5 rows x 30 columns]

In [22]:
df_frt = pd.DataFrame(feature, columns = )

SyntaxError: invalid syntax (<ipython-input-22-619a491289fc>, line 1)

In [23]:
#500 rows for training
X_train= feature[:500]
Y_train= label[:500]

#35 rows for validation

X_val = feature[500:535]
Y_val = label[500:535]

#34 rows for testing
X_test = feature[535:]
Y_test= label[535:]


In [24]:
feature.shape

(569, 30)

In [25]:
label.shape

(569,)

In [26]:
X_train.shape


(500, 30)

In [27]:
#Deep Learning Model

In [28]:
X_test

array([[ 1.82414032,  0.36543133,  1.88778669, ...,  1.5256103 ,
         0.28512459, -0.45750286],
       [ 0.04053117,  0.75870568,  0.07418218, ...,  0.32879975,
        -0.32801426, -0.02415117],
       [-0.69222545,  1.19852137, -0.64252731, ...,  0.24657612,
        -0.1581473 ,  0.87303092],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [29]:
Y_test


array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [30]:
#Creation of Neural Network

In [52]:
model = Sequential()
#For 1 tumor we are giving 30 input values which are the features and in the result
#we need 1 value that can either be 0 or 1.

model.add(Dense(15, activation = 'relu', input_dim = 30))
model.add(Dense(15 , activation = 'relu'))
model.add(Dense(15 , activation = 'relu'))

model.add(Dense(1, activation = "sigmoid"))

model.compile(loss = "binary_crossentropy", optimizer = 'adam', metrics = ['accuracy'])

In [55]:
model.fit(X_train, Y_train, batch_size=1, epochs =10, validation_data  = (X_val, Y_val))

Epoch 1/10
500/500 [==============================] - 1s 1ms/step - loss: 0.0410 - accuracy: 0.9840 - val_loss: 0.0694 - val_accuracy: 0.9714
Epoch 2/10
500/500 [==============================] - 1s 1ms/step - loss: 0.0270 - accuracy: 0.9920 - val_loss: 0.0633 - val_accuracy: 0.9714
Epoch 3/10
500/500 [==============================] - 1s 1ms/step - loss: 0.0256 - accuracy: 0.9900 - val_loss: 0.1284 - val_accuracy: 0.9429
Epoch 4/10
500/500 [==============================] - 1s 1ms/step - loss: 0.0149 - accuracy: 0.9940 - val_loss: 0.1464 - val_accuracy: 0.9429
Epoch 5/10
500/500 [==============================] - 1s 1ms/step - loss: 0.0131 - accuracy: 0.9940 - val_loss: 0.1754 - val_accuracy: 0.9429
Epoch 6/10
500/500 [==============================] - 1s 1ms/step - loss: 0.0099 - accuracy: 0.9960 - val_loss: 0.1904 - val_accuracy: 0.9429
Epoch 7/10
500/500 [==============================] - 1s 1ms/step - loss: 0.0248 - accuracy: 0.9840 - val_loss: 0.1750 - val_accuracy: 0.9429
Epoch 

In [56]:
model.evaluate(X_test, Y_test)

2/2 [==============================] - 0s 997us/step - loss: 0.0160 - accuracy: 1.0000


[0.0159640870988369, 1.0]

In [45]:
#We need to shuffle the dataset to get the best output


In [59]:
sample  = X_test[0]

In [60]:
sample.shape

(30,)

In [62]:
sample = np.reshape(sample,(1,30))

In [65]:
if model.predict(sample)[0][0]>0.5:
    print("Benign")
else:
    print("Malignant")

Malignant


In [66]:
Y_test[0]

0

In [68]:
#Example 1 of test

for i in range(10):
    
    sample = X_test[i]
    sample = np.reshape(sample, (1,30))
    
    print("Predict")
    
    if model.predict(sample)[0][0]>0.5:
        print("Benign")
    else:
        print("Malignant")
        
    print("Actual")
    
    if Y_test[i]==1:
        print("Benign")
    else:
        print("Malignant")
        
    print("-----")    

Predict
Malignant
Actual
Malignant
-----
Predict
Malignant
Actual
Malignant
-----
Predict
Benign
Actual
Benign
-----
Predict
Benign
Actual
Benign
-----
Predict
Benign
Actual
Benign
-----
Predict
Benign
Actual
Benign
-----
Predict
Benign
Actual
Benign
-----
Predict
Benign
Actual
Benign
-----
Predict
Benign
Actual
Benign
-----
Predict
Benign
Actual
Benign
-----


In [70]:
#Example 2 of test

for i in range(11,21):
    
    sample = X_test[i]
    sample = np.reshape(sample, (1,30))
    
    print("Predict")
    
    if model.predict(sample)[0][0]>0.5:
        print("Benign")
    else:
        print("Malignant")
        
    print("Actual")
    
    if Y_test[i]==1:
        print("Benign")
    else:
        print("Malignant")
        
    print("-----")    

Predict
Benign
Actual
Benign
-----
Predict
Benign
Actual
Benign
-----
Predict
Benign
Actual
Benign
-----
Predict
Benign
Actual
Benign
-----
Predict
Benign
Actual
Benign
-----
Predict
Benign
Actual
Benign
-----
Predict
Benign
Actual
Benign
-----
Predict
Benign
Actual
Benign
-----
Predict
Benign
Actual
Benign
-----
Predict
Benign
Actual
Benign
-----


### CONCLUSION

**In the data above we predicted if a cancer is malignant or benign, and it worked pretty well, when we inserted the test values as samples. 
All the predicted and actual results came out to be the same.**